# Generated by Django 3.2.13 on 2022-06-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', help_text='Task Status', max_length=50, verbose_name='Task Status'),
        ),
        migrations.AlterField(
            model_name='item',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='status'),
        ),
    ]
